In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('D:\\data_mining\\tuan2\\ionosphere.data', header=None)
print(df)

     0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
346   1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

          9   ...       25       26       27       28       29 

In [3]:
df.pop(df.columns[-1])
print(df)

     0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
346   1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

          9   ...       24       25       26       27       28 

In [4]:
#array
array = df.values
print(array)

point1 = array[0,:]
point2 = array[1,:]
point3 = array[2,:]

#p = 1
dist01_2 = np.linalg.norm(point1 - point2, 1)
dist01_3 = np.linalg.norm(point1 - point3, 1)

#p = 2
dist1_2 = np.linalg.norm(point1 - point2, 2)
dist1_3 = np.linalg.norm(point1 - point3, 2)

#p = inf
dist11_2 = np.linalg.norm(point1 - point2, np.inf)
dist11_3 = np.linalg.norm(point1 - point3, np.inf)

print(dist01_2)
print(dist01_3)

print(dist1_2)
print(dist1_3)

print(dist11_2)
print(dist11_3)

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
13.080950000000001
5.359709999999999
2.7763589251571923
1.1697276018372824
1.12221
0.45772


In [5]:
def Distanace(X, Y, p):
    if p == np.inf:
        return max(np.abs(X - Y))
    return np.sum(np.abs(X - Y) ** p) ** (1 / p)

In [6]:
Dist_1 = np.zeros((50, 50))
Dist_2 = np.zeros((50, 50))
Dist_inf = np.zeros((50, 50))

for i in range(0 , 50):
    for j in range(0, 50):
        Dist_1[i][j] = Distanace(array[i], array[j], 1)
        Dist_2[i][j] = Distanace(array[i], array[j], 2)
        Dist_inf[i][j] = Distanace(array[i], array[j], np.inf)

print(Dist_1, "\n")
print(Dist_2, "\n")
print(Dist_inf, "\n")

[[ 0.      13.08095  5.35971 ... 15.98462  7.74504 21.06072]
 [13.08095  0.      15.80038 ... 17.53049 17.89603 18.96035]
 [ 5.35971 15.80038  0.      ... 15.88161  4.16871 19.98939]
 ...
 [15.98462 17.53049 15.88161 ...  0.      16.76954 19.93674]
 [ 7.74504 17.89603  4.16871 ... 16.76954  0.      21.72226]
 [21.06072 18.96035 19.98939 ... 19.93674 21.72226  0.     ]] 

[[0.         2.77635893 1.1697276  ... 3.74495828 1.59090253 4.40093478]
 [2.77635893 0.         3.38003304 ... 3.90492063 3.91433755 3.96620878]
 [1.1697276  3.38003304 0.         ... 3.82755203 0.97067099 4.35585992]
 ...
 [3.74495828 3.90492063 3.82755203 ... 0.         4.15300217 4.81090468]
 [1.59090253 3.91433755 0.97067099 ... 4.15300217 0.         4.89191224]
 [4.40093478 3.96620878 4.35585992 ... 4.81090468 4.89191224 0.        ]] 

[[0.      1.12221 0.45772 ... 1.85243 0.5728  1.60536]
 [1.12221 0.      1.10868 ... 1.93035 1.45054 1.63147]
 [0.45772 1.10868 0.      ... 2.      0.42872 1.54591]
 ...
 [1.85243 