In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('D:\\data_mining\\tuan2\\kddcup.data.corrected', header=None)
print(df)

         0    1     2   3    4      5   6   7   8   9   ...   32   33   34  \
0         0  tcp  http  SF  215  45076   0   0   0   0  ...    0  0.0  0.0   
1         0  tcp  http  SF  162   4528   0   0   0   0  ...    1  1.0  0.0   
2         0  tcp  http  SF  236   1228   0   0   0   0  ...    2  1.0  0.0   
3         0  tcp  http  SF  233   2032   0   0   0   0  ...    3  1.0  0.0   
4         0  tcp  http  SF  239    486   0   0   0   0  ...    4  1.0  0.0   
...      ..  ...   ...  ..  ...    ...  ..  ..  ..  ..  ...  ...  ...  ...   
4898426   0  tcp  http  SF  212   2288   0   0   0   0  ...  255  1.0  0.0   
4898427   0  tcp  http  SF  219    236   0   0   0   0  ...  255  1.0  0.0   
4898428   0  tcp  http  SF  218   3610   0   0   0   0  ...  255  1.0  0.0   
4898429   0  tcp  http  SF  219   1234   0   0   0   0  ...  255  1.0  0.0   
4898430   0  tcp  http  SF  219   1098   0   0   0   0  ...  255  1.0  0.0   

           35    36   37    38   39   40       41  
0        0.

In [2]:
categorical_columns = df.select_dtypes(include=['object']).columns
print("Categorucal attributes:", categorical_columns)
categorical_data = df[categorical_columns]
print("Categorical Data:\n", categorical_data)

Categorucal attributes: Index([1, 2, 3, 41], dtype='int64')
Categorical Data:
           1     2   3        41
0        tcp  http  SF  normal.
1        tcp  http  SF  normal.
2        tcp  http  SF  normal.
3        tcp  http  SF  normal.
4        tcp  http  SF  normal.
...      ...   ...  ..      ...
4898426  tcp  http  SF  normal.
4898427  tcp  http  SF  normal.
4898428  tcp  http  SF  normal.
4898429  tcp  http  SF  normal.
4898430  tcp  http  SF  normal.

[4898431 rows x 4 columns]


In [3]:
#- Kiểm tra giá trị giống nhau
print("So luong dong giong nhau:", categorical_data.duplicated().sum())

##loại bỏ các dòng giống nhau
df1 = categorical_data.drop_duplicates()
print("Du lieu sau khi xoa nhung dong giong nhau: \n", df1)

So luong dong giong nhau: 4897822
Du lieu sau khi xoa nhung dong giong nhau: 
           1         2     3                 41
0        tcp      http    SF           normal.
1288     tcp      http    S2           normal.
1484     tcp      http    S1           normal.
2062     tcp      smtp    SF           normal.
2067     udp  domain_u    SF           normal.
...      ...       ...   ...               ...
4574130  tcp       bgp   REJ          neptune.
4575586  tcp    Z39_50   REJ          neptune.
4578870  tcp      smtp    SF          neptune.
4579297  tcp     other  RSTO          neptune.
4810949  tcp    telnet  RSTO  buffer_overflow.

[609 rows x 4 columns]


In [83]:
array = df1.values
array = array[: 100]
array = np.array(array)

In [84]:
def Overlap(X, Y):
    sim = 0
    for i in range(len(X)):
        if X[i] == Y[i]:
            sim = sim + 1/len(X)
    return sim

In [85]:
def tan_suat_xuat_hien_nguoc(X, Y):
    sim = 0
    for i in range(len(X)):
        if X[i] == Y[i]:
            sim = sim + 1/len(X)
        if X[i] != Y[i]:
            count1 = np.sum(array[:, i] == X[i])
            count2 = np.sum(array[:, i] == Y[i])
            sim = sim + 1/len(X) * 1/(1 + np.log(count1) * np.log(count2))
    return sim

In [88]:
Overlap_array = np.zeros((100, 100))
tsxhn_array = np.zeros((100, 100))

for i in range(0 , 100):
    for j in range(0, 100):
        Overlap_array[i][j] = Overlap(array[i], array[j])
        tsxhn_array[i][j] = tan_suat_xuat_hien_nguoc(array[i], array[j])

print(Overlap_array, "\n")
print(tsxhn_array)

[[1.   0.75 0.75 ... 0.25 0.25 0.25]
 [0.75 1.   0.75 ... 0.25 0.25 0.25]
 [0.75 0.75 1.   ... 0.25 0.25 0.25]
 ...
 [0.25 0.25 0.25 ... 1.   0.5  0.5 ]
 [0.25 0.25 0.25 ... 0.5  1.   0.75]
 [0.25 0.25 0.25 ... 0.5  0.75 1.  ]] 

[[1.         1.         0.79448861 ... 0.34763716 0.36660768 0.36660768]
 [1.         1.         1.         ... 0.57269646 0.59528745 0.59528745]
 [0.79448861 1.         1.         ... 0.37528204 0.39105564 0.39105564]
 ...
 [0.34763716 0.57269646 0.37528204 ... 1.         0.6099475  0.6099475 ]
 [0.36660768 0.59528745 0.39105564 ... 0.6099475  1.         0.86327856]
 [0.36660768 0.59528745 0.39105564 ... 0.6099475  0.86327856 1.        ]]


In [89]:
neighbor_Overlap = np.argsort(-Overlap_array, axis=1)
neighbor_tsxhn = np.argsort(-tsxhn_array, axis=1)

print(neighbor_Overlap, "\n")
print(neighbor_tsxhn)

[[ 0  1  2 ... 97 98 99]
 [ 1  0  2 ... 27 26 23]
 [ 2  0  1 ... 27 26 23]
 ...
 [97 49 81 ... 13  8  4]
 [98 86 85 ... 13  8  4]
 [99 87 86 ... 13  8  4]] 

[[ 0  1  5 ... 38 79 47]
 [ 0  1  2 ... 51 79 47]
 [ 1  2 15 ... 38 79 47]
 ...
 [97 77 82 ...  8 17 13]
 [98 93 92 ...  8 17 13]
 [99 93 92 ...  8 17 13]]
